### ISSUE TITLE
Possible leak?

### ISSUE THREAD

**Issue by script3r** [duosecurity/duo_unix#104]
https://github.com/duosecurity/duo_unix/blob/4358b725e8d8da50ff5a8d7834bcd0b45bc0a790/lib/duo.c#L211

What happens if the `asprintf` allocation succeeds, however the check `ctx->argc + 1 < (sizeof(ctx->argv) / sizeof(ctx->argv[0]))` fails? Shouldn't we free `p` right there?

In that case, `p` wouldn't be assigned to one of the `ctx->argv` entries, which means it wouldn't be `free()`d up by `duo_reset`, correct?

**Comment by xdesai** [comment]
Hi Isaac,
Thanks for raising this issue. It does appear that there would be a leak in that case. Are you interested in making a pull request to fix the leak?

**Comment by xdesai** [comment]
Resolved via https://github.com/duosecurity/duo_unix/pull/119
