### ISSUE TITLE
[Bug] Duo Mobile App in iOS Approve button denies permission

### ISSUE THREAD

**Issue by neliyacf** [duosecurity/duo_unix#105]
[Bug]
Duo Mobile App iOS
While trying to connect to a remote server through FortiClient, I have enabled two factor authentication in my mobile. And clicking on Approve (green tick) gives _**'Permission Denied ~455'**_ error whereas after clicking on Deny (red cross) it allows me to connect.
Steps to replicate: 
- Enable duo security two factor authentication on your phone.
- Connect to remote server through Forticlient
- When prompted click on Approve alert message **_'Permission Denied ~455'_**
- Try to connect again , click on Deny button, then 'it was a mistake', then you will be connected .

**Comment by DuoKristina** [comment]
Hello neliyacf,

Can you please contact Duo's Technical Support about this isssue, as it's not specifically a problem with the Duo Unix application? https://duo.com/support

Thanks!
