### ISSUE TITLE
Allow multiple PAM profiles

### ISSUE THREAD

**Issue by ghost** [duosecurity/duo_unix#107]
I have multiple services authenticating through Duo on the same Linux system, all of which go through PAM. I would love to be able to define different applications for each service (and therefore different policies), but currently, this can't be done. An example would be requiring a certain policy set for VPN connections (the system is the VPN server), and a different policy set for interactive connections TO that server (there are people that can connect to the VPN that can't log in to the VPN server itself).

**Comment by adrikim** [comment]
Hey Justin,

Sorry about the late response! We're tracking your feature request internally now, and while I can't say for sure when, we'll see if we have room for it to be done sometime soon-ish. :)

Thanks for using Duo!

**Comment by AaronAtDuo** [comment]
Closing out this old issue
