### ISSUE TITLE
be better about using best RPM packaging practices

### ISSUE THREAD

**Issue by qralston** [duosecurity/duo_unix#110]
Before I begin: a hearty _thank you_ to Duo for embracing the open source process for implementing Duo for Linux, and for going the extra mile to provide duo_unix RPM packages via a yum repository.

I intend the following comments as constructive criticism, to further improve the quality of the available duo_unix packages.

I can't speak to Debian packages, but in terms of RPM, there are certain best practices that packagers should follow, which unfortunately aren't always obvious, or very well documented. The build process that produces the packages located at http://pkg.duosecurity.com/ follows some of those practices, but could do better.

# Development files should be in a separate -devel package

Files that are only useful when developing applications to use with the main library/program should be packaged in a separate -devel package, so that people who only want to use the main application don't need to install those additional files.

For duo_unix, the ``*.la``, ``*.h``, ``*.pc``, and ``duo.3*`` files should be located in a duo_unix-devel package.

Note that the ``rpmlint`` tool catches some of these files:

```
duo_unix.x86_64: W: devel-file-in-non-devel-package /usr/include/duo.h
duo_unix.x86_64: W: devel-file-in-non-devel-package /usr/include/shell.h
duo_unix.x86_64: W: devel-file-in-non-devel-package /usr/include/util.h
duo_unix.x86_64: W: devel-file-in-non-devel-package /usr/lib64/pkgconfig/libduo.pc
```

# Generically-named include files should be located within an application-specific subdirectory

While the ``duo.h`` include file is fairly unique, the ``shell.h`` and ``util.h`` include files have very generic names. Locating these include files in the top-level ``/usr/include`` directory should be avoided for that reason, because if every package behaved that way, lots of package conflicts would result.

For example, on a RHEL7 host, 46 different packages contribute files named ``util.h`` to ``/usr/include``, but because they all do so via subdirectories (e.g., ``/usr/include/pulse/util.h``), they don't conflict. If instead all of those packages contributed ``/usr/include/util.h``, chaos would result.

# Use the RPM %doc macro (in %files) instead of manually installing files in /usr/share/doc

Files that an RPM package contribute to the ``/usr/share/doc`` tree should be packaged by using the ``%doc`` macro in the ``%files`` section, instead of having the ``make install`` step install the files.

This is because the ``/usr/share/doc`` subdirectory may or may not have versioned subdirectories—that is, ``/usr/share/doc/foo-1.0.0`` versus ``/usr/share/doc/foo``. On recent Fedora, subdirectories of ``/usr/share/doc`` aren't versioned, but on all released versions of RHEL, they are. The ``%doc`` macro will Do The Right Thing.

# Inappropriate use (or absence) of compression

Generally speaking, SELinux module files shouldn't be compressed, and man pages _should_ be compressed. But the duo_unix packages compress the authlogin_duo.pp SELinux module, and don't compress the man pages.

Again, rpmlint will catch this:

```
duo_unix.x86_64: W: manpage-not-compressed gz /usr/share/man/man3/duo.3
duo_unix.x86_64: W: manpage-not-compressed gz /usr/share/man/man8/login_duo.8
duo_unix.x86_64: W: manpage-not-compressed gz /usr/share/man/man8/pam_duo.8
```

# Start release numbers with 1, not 0

For each new version of the package, the release number should be reset to 1, *not 0*.

This guideline is useful in cases where the software developers provide official RPM packages, but there is a delay between when a new version of the software is released, and when the packages are available. If you really need a fix/feature that is in a newer version, but that version hasn't been packaged yet, you can locally build and package that version with a release of (e.g.) ``0.local``. That way, when the official upstream packages are released for the new version, because the release tag was reset to 1 in the official packages, those new packages will supersede your ``0.local`` release packages.

In contrast, if the upstream packages reset the release to 0 with each new version, then if you needed to jump the gun and temporarily build/package that new version locally, when the official upstream packages are released, they won't be newer than your packages. So your hosts won't automatically upgrade to the official upstream packages until the next release (the ``1`` release) drops.

For this reason, all "official" packages should always reset the RPM release to 1 with each new version of the software that is packaged, never 0. (This is considered a good packaging practice, even if you're very diligent about providing official RPM packages promptly.)

#  Additional notes

My pull request #109 contributes an RPM spec file that corrects the above issues.

I know (per issue #108) that Duo is generating the packages located at http://pkg.duosecurity.com/ a different way, but perhaps my spec file could be useful in implementing the above suggestions into that build process?

**Comment by qralston** [comment]
A few items I forgot:

# Support debuginfo packages

The standard packaging procedure for Fedora/RHEL systems is to compile and link binaries in the package with full debugging enabled. As part of the packaging process, the debugging information is stripped from the binaries, and packaged in a separate `debuginfo` package.

(On Fedora/RHEL systems, the `redhat-rpm-config` package provides scripts and macros to automate the creation of the `debuginfo` package.)

The packages available at http://pkg.duosecurity.com/ do not follow these packaging guidelines. Instead, there are no `debuginfo` packages available, and the core packages contain unstripped binaries.

`rpmlint` will catch this:

```
duo_unix.x86_64: W: unstripped-binary-or-object /usr/sbin/login_duo
duo_unix.x86_64: W: unstripped-binary-or-object /lib64/security/pam_duo.so
```

# Correct placement of PAM shared libraries

On RHEL6 and earlier, `/lib` and `/lib64` were separate directories. On RHEL7 and Fedora, `/lib` and `/lib64` were removed in favor of `/usr/lib` and `/usr/lib64`.

While there are symbolic links (from `/lib` to `/usr/lib`, and from `/lib64` to `/usr/lib64`) to maintain backward compatibility, new packages should respect the correct location for libraries on the distribution for which the package is built.

The `duo_unix` packages available at http://pkg.duosecurity.com/ do not do this consistently. For example, the RHEL7 package for x86_64 places the `pam_duo.so` shared object in `/lib64/security` (incorrect for RHEL7), instead of `/usr/lib64/security` (correct for RHEL7).

**Comment by jsbillings** [comment]
We also maintain our own RPM spec file due to issues with the provided RPMs, so to pile on to your already exhaustive list of requested features, I think Duo should also include SELinux modules in a subpackage, as described by this [Fedora packaging draft](https://fedoraproject.org/wiki/PackagingDrafts/SELinux).  Putting the Duo selinux module in a subpackage means you can properly set up requirements so 'semodule' is installed and can install the SELinux module.  

As it stands, if you install the provided Duo packages and don't have the policycoreutils package installed but have SELinux enabled, you'll end up with a system without the appropriate authlogin_duo SELinux module installed, and SELinux will block Duo from working.

On a related note, the RPM postinstall scriptlet does a `chmod 4755 /usr/sbin/login_duo`, which seems rather odd and inappropriate to have as part of %postinstall.

**Comment by qralston** [comment]
@xdesai, ping. It's been more than half a year since I submitted this issue, and the most recent (1.10.5) binary RPMs still have all of these issues.

We would prefer to just use the binary RPMs that Duo provides, but due to all of these issues, and the lack of adequate SELinux support (see pull request #138), we essentially have no choice but to roll our own Duo packages.

**Comment by xdesai** [comment]
Hey guys :)
Just wanted to respond back and say I hear ya.
I'll forward the latest bump onto our product management team. If you guys have not filed official feature requests with Duo please contact support and do so! That's a great way to help get stuff prioritized because it gives us hard numbers on the desire for functionality like this.
Sorry I can't give you better news at this time!

**Comment by qralston** [comment]
@xdesai, just FYI, I filed support case 00295737 on 2018-10-19 to help boost the priority of this request. I was told that a feature request had been created. Is there any news on addressing these issues?

**Comment by xdesai** [comment]
Thank for filing the feature requests for this and the SELinux things! I would encourage any others following this thread to do the same.
Sadly, I don't have any update for you at this time but we'll keep you posted when we do.

**Comment by AaronAtDuo** [comment]
This is not on the roadmap at this time.  We have noticed repackagers publishing to Fedora and Debian repos that have addressed some of these issues.
