### ISSUE TITLE
Support group names with spaces

### ISSUE THREAD

**Issue by wgj** [duosecurity/duo_unix#113]
Currently `duo_common_ini_handler` [only expects spaces](https://github.com/duosecurity/duo_unix/blob/master/lib/util.c#L68) to be the delimiter between groups, and not part of the group name itself.

Using the documentation's example:
``` bash
groups = users,!wheel,!*admin guests
```

But I'd like to be able to use spaces, which is common when groups are provided by Active Directory/SSSD:
``` bash
groups = users,!wheel,!*admin guests "group with spaces"
```

I have a solution nearly finished that I'd like to submit a pull request for, but it's a bit spaghetti-like to maintain the delimiter state for `strtok`, and I _think_ it would be easier to maintain with `strsep` (which is recommended in `man 3 strtok` for macOS), which is recommended if you aren't using C90 for portability.

Would you mind if I made a PR for this, and is it important to use `strtok`?

**Comment by vbscott** [comment]
We just updated the code on our GitHub to fix this issue, thank you!
