### ISSUE TITLE
Autopush message doesn't appear until after 2FA interaction

### ISSUE THREAD

**Issue by feld** [duosecurity/duo_unix#115]
When using autopush with duo_unix and you ssh to a server, the output looks like this:

```
$ ssh feld@somehost
Autopushing login request to phone...
Success. Logging you in...
```

The problem is that the first line "Autopushing login request to phone..." doesn't appear until after the 2FA interaction has completed. This message should immediately print instead of leaving the user with the impression that the command is hanging.

**Comment by BradleyHiggins** [comment]
The last comment in #73 has an in-depth answer to this issue. Unfortunately there's not much we can do to solve this one.

Thanks for using Duo!
