### ISSUE TITLE
Login fails if first password is incorrect but subsequent password is correct

### ISSUE THREAD

**Issue by macrotex** [duosecurity/duo_unix#117]
We have the Duo pam module installed on Debian jessie machines. We are seeing this behavior.

1. ssh joeuser@myserver.example.com
2. When prompted for the password, type in the WRONG password.
3. You will be prompted for the password again. This time type in the CORRECT password.
4. When prompted for Duo, proceed with a correct Duo response.
5. The ssh connection fails with the message "Write failed: Broken pipe".

**Comment by DuoKristina** [comment]
Have you checked your socket timeouts and/or ServerAlive/ClientAlive settings?

Please [contact Duo Support](https://duo.com/support) for assistance troubleshooting your deployment. They can review your sshd/pam configuration and debug log output with you.

**Comment by kcgthb** [comment]
Hi there, 

I'd like to report the exact same issue, where SSH connection fails with "broken pipe" when a wrong password is initially entered. 
This happens on CentOS 7, following the instructions and using the configuration examples at https://duo.com/docs/duounix

I would also like to add that we obeserve that exact same behavior on a large variety of machines, running different distributions and using a variety of SSH authentication mechanisms (password, GSSAPI/Kerberos, pubkeys...)

Any insight would be appreciated.
