### ISSUE TITLE
GECOS parsing makes gross assumptions in pam_sm_authenticate -- pam_duo.c:135,136,239-245

### ISSUE THREAD

**Issue by kaiwetlesen** [duosecurity/duo_unix#130]
According to many GECOS references, this password field is typically delimited by commas ( , ) instead of front slashes ( / ). See [man -s5 passwd](https://www.freebsd.org/cgi/man.cgi?query=passwd&sektion=5) on any BSD, AIX, or Linux installation. The current Duo parser requires a format that breaks applications using the canonical format.

It is recommended that both the delimiter and the GECOS subfield number be configurable as distributions do not specify which GECOS subfield contains a user's email or what-have-you. For example, the Linux manual specifies the GECOS field thus:
```
       GECOS       This  field  (sometimes  called  the "comment field") is optional and used only for
                   informational purposes.  Usually, it contains the  full  username.   Some  programs
                   (for example, finger(1)) display information from this field.

                   GECOS  stands  for  "General  Electric  Comprehensive  Operating System", which was
                   renamed to GCOS when GE's large systems division was  sold  to  Honeywell.   Dennis
                   Ritchie  has  reported: "Sometimes we sent printer output or batch jobs to the GCOS
                   machine.  The gcos field in the password file was a place to stash the  information
                   for the $IDENTcard.  Not elegant."
```
While OpenBSD and FreeBSD specifies:
```
     The gecos field normally contains comma (`,') separated subfields as fol-
     lows:

	   name	   user's full name
	   office  user's office number
	   wphone  user's work phone number
	   hphone  user's home phone number

     The full name may contain an ampersand (`&') which	will be	replaced by
     the capitalized login name	when the gecos field is	displayed or used by
     various programs such as finger(1), sendmail(8), etc.

     The office	and phone number subfields are used by the finger(1) program,
     and possibly other	applications.
```

**Comment by xdesai** [comment]
Thank you for the feature request!
I have some disappointing news that this feature isn't an extremely high priority for us at this time. We'd definitely recommend you fork Duo Unix if this functionality is a requirement for you in the near future.
I'll make sure we're tracking this internally and I'll definitely comment back here with any updates.

Thanks for using Duo!

**Comment by kaiwetlesen** [comment]
@xdesai thanks for the update. I've forked the repo for this plugin and am working on alterations now.

**Comment by DuoKristina** [comment]
Duo Unix 1.11.0 includes the `gecos_username_pos` and `gecos_delim` configurable options.
https://duo.com/docs/duounix-notes#duo_unix-1.11.0-october-2018
