### ISSUE TITLE
./configure failes on centos

### ISSUE THREAD

**Issue by toninog** [duosecurity/duo_unix#14]
Hi,

When trying to install the duo_unix 1.6 - I am getting this error:

duo_unix-1.6]# ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... Invalid configuration `i686-pc-linux-': machine`i686-pc-linux' not recognized
configure: error: /bin/sh autotools/config.sub i686-pc-linux- failed

I would appreciate a tip on how to resolve this ?

Thanks

**Comment by hananeam1991** [comment]
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking build system type... Invalid configuration `libalize.a': machine `libalize.a' not recognized
configure: error: /bin/bash ./config.sub libalize.a failed

**Comment by hananeam1991** [comment]
hi 
when i want to compile alize i run make but i have this error please if someone have a solution for this error :
Making all in src
make[1] : on entre dans le répertoire « /home/hanane/Bureau/PACK-ALIZE/alize-core-master/src »
rm -f libalize.a
ar cru libalize.a alizeString.o AudioFileReader.o AudioFrame.o AudioInputStream.o AutoDestructor.o CmdLine.o Config.o ConfigChecker.o ConfigFileReaderAbstract.o ConfigFileReaderRaw.o ConfigFileReaderXml.o ConfigFileWriter.o Distrib.o DistribGD.o DistribGF.o DistribRefVector.o DoubleSquareMatrix.o Exception.o Feature.o FeatureFileList.o FeatureFileReader.o FeatureFileReaderAbstract.o FeatureFileReaderHTK.o FeatureFileReaderRaw.o FeatureFileReaderSPro3.o FeatureFileReaderSPro4.o FeatureFileReaderSingle.o FeatureFileWriter.o FeatureFlags.o FeatureInputStream.o FeatureInputStreamModifier.o FeatureMultipleFileReader.o FeatureServer.o FileReader.o FileWriter.o FrameAcc.o FrameAccGD.o FrameAccGF.o Histo.o LKVector.o Label.o LabelFileReader.o LabelServer.o LabelSet.o Mixture.o MixtureDict.o MixtureFileReader.o MixtureFileReaderAbstract.o MixtureFileReaderAmiral.o MixtureFileReaderRaw.o MixtureFileReaderXml.o MixtureFileWriter.o MixtureGD.o MixtureGDStat.o MixtureGF.o MixtureGFStat.o MixtureServer.o MixtureServerFileReader.o MixtureServerFileReaderAbstract.o MixtureServerFileReaderRaw.o MixtureServerFileReaderXml.o MixtureServerFileWriter.o MixtureStat.o Object.o Seg.o SegAbstract.o SegCluster.o SegServer.o SegServerFileReaderAbstract.o SegServerFileReaderRaw.o SegServerFileWriter.o StatServer.o ULongVector.o ViterbiAccum.o XLine.o XList.o XListFileReader.o XmlParser.o 
ar: le modificateur « u » est ignoré puisque « D » est le défaut (consultez « U »)
ranlib libalize.a
make[1] : on quitte le répertoire « /home/hanane/Bureau/PACK-ALIZE/alize-core-master/src »
make[1] : on entre dans le répertoire « /home/hanane/Bureau/PACK-ALIZE/alize-core-master »
make[1]: rien à faire pour « all-am ».
make[1] : on quitte le répertoire « /home/hanane/Bureau/PACK-ALIZE/alize-core-master »
mkdir -p lib ; mv src/libalize.a lib/libalize_Linux_x86_64.a
