### ISSUE TITLE
pam_info(3) status messages not reliably communicated

### ISSUE THREAD

**Issue by qralston** [duosecurity/duo_unix#164]
## Summary

When pam_duo.so is used in the PAM stack, and `autopush = yes` is set in `/etc/duo/pam_duo.conf`, depending on the login mechanism, status messages from pam_duo.so are not always properly communicated to the user.

Specifically, these status messages:

```
Autopushing login request to phone...

Pushed a login request to your device...
```

…are typically not seen by the user for remote connections via ssh. This can be confusing if the user does not realize that he has logged into a system with autopush enabled and does not have his mobile device near him: for all practical purposes, his login attempt hangs after he enters his password.

Curiously, though, if the user denies the push request, **then** the _Autopushing login request to phone..._ message is visible.

Here's an example, logging in with autopush enabled, and approving the push request:

```
$ ssh -o PreferredAuthentications=keyboard-interactive host.example.org echo "logged in"
Password: 
<-- at this point I approve the push request on my phone
logged in
```

However, if I deny the first push request, then I **do** see the autopush notification, just before the login denied message:

```
$ ssh -o PreferredAuthentications=keyboard-interactive host.example.org echo "logged in"
Password: 
<-- at this point I deny the push request on my phone
Autopushing login request to phone...
Login request denied.

Password: 
<-- at this point I approve the push request on my phone
logged in
```

This is bizarre. It suggests that the `pam_info()` calls don't actually get communicated to the remote user unless a conversation function is triggered.

Specifically, in the Linux PAM source code, `pam_info()` is just a special case of `pam_prompt()`:

```
#define pam_info(pamh, fmt...) pam_prompt(pamh, PAM_TEXT_INFO, NULL, fmt)
```

And message styles are:

```
/* Message styles */

#define PAM_PROMPT_ECHO_OFF	1
#define PAM_PROMPT_ECHO_ON	2
#define PAM_ERROR_MSG		3
#define PAM_TEXT_INFO		4
```

So it looks like `PAM_TEXT_INFO` messages don't get passed to the remote ssh user until one of the conversation functions (that requires a response from the user) is called. And if no conversation function is called, the  `PAM_TEXT_INFO` messages are never communicated at all.

I'm not convinced that this is the fault of pam_duo. If anything, this looks more like a bug in OpenSSH. I'll continue to dig at this.

## Addendum

I initially thought the problem was that pam_duo.so was simply using `printf()` to communicate status messages to the user. But after digging into the code more closely, I realized that `pam_sm_authenticate()` sets up appropriate conversation functions when PAM is in use:

```
    duo_set_conv_funcs(duo, __duo_prompt, __duo_status, pamh);
```

Those functions are:

```
static void
__duo_status(void *arg, const char *msg)
{
    pam_info((pam_handle_t *)arg, "%s", msg);
}

static char *
__duo_prompt(void *arg, const char *prompt, char *buf, size_t bufsz)
{
    char *p = NULL;

    if (pam_prompt((pam_handle_t *)arg, PAM_PROMPT_ECHO_ON, &p,
        "%s", prompt) != PAM_SUCCESS || p == NULL) {
        return (NULL);
    }
    strlcpy(buf, p, bufsz);
    free(p);
    return (buf);
}
```

So my initial report was incorrect, because it misdiagnosed the problem.

**Comment by qralston** [comment]
OK, this is definitely not pam_duo's fault.

`pam_echo.so` uses the same `pam_info()` function that pam_duo does. So I can use pam_echo in the PAM auth stack for testing, as follows:

```
auth        required      pam_echo.so [about to call pam_duo.so]
auth        required      pam_duo.so
auth        required      pam_echo.so [finished calling pam_duo.so]
```

If I login on a virtual console, all of the messages are communicated correctly:

```
host login: username
Password:
about to call pam_duo.so
Autopushing login request to phone...

Pushed a login request to your device...
<-- at this point I approve the push request on my phone
Success. Logging you in...
finished calling pam_duo.so
```

But when logging in remotely via ssh, the `PAM_TEXT_INFO` messages aren't seen unless they are "flushed" by calling a conversation function:

```
$ ssh -o PreferredAuthentications=keyboard-interactive host.example.org echo "logged in"
Password: 
<-- at this point I deny the push request on my phone
about to call pam_duo.so
Autopushing login request to phone...
Login request denied.
finished calling pam_duo.so

Password: 
<-- at this point I approve the push request on my phone
logged in
```

Furthermore, if I trace the sshd daemon during the login process, I see a `write()` call with the _Autopushing login request to phone..._ text trigger at the correct time. But a network trace shows that sshd only ACKs the packet from the client that contains the password; there's no data in the reply.

Since pam_echo (part of the official Linux PAM project) demonstrates the same problem with sshd not passing `PAM_TEXT_INFO` messages back to the client, this definitely rules out pam_duo as being the culprit.

I will now take this issue upstream, and close this issue.

I apologize for the noise, but perhaps this issue will benefit others who stumble upon the same problem with sshd.

**Comment by BradleyHiggins** [comment]
I think this is the same issue as https://github.com/duosecurity/duo_unix/issues/73, which has a good detailed description of what's going on at the end of it, here https://github.com/duosecurity/duo_unix/issues/73#issuecomment-236204410

**Comment by qralston** [comment]
Yup, this is an unintentional dupe of #73; thanks for the catch.

There's at least a chance of getting this fixed in OpenSSH proper; see my recent comment on #73.
