### ISSUE TITLE
pam_duo fails to build on Solaris 11

### ISSUE THREAD

**Issue by aaronwmorris** [duosecurity/duo_unix#195]
## Summary
pam_duo fails to build on Solaris 11

## Steps to reproduce
1. make fails at the make step for pam_duo

## Specs
- OS version: SunOS atlxx000001 5.11 11.4.23.69.3 i86pc i386 i86pc
- OS arch: i386/x86_64 
- Using pam_duo

## Configure
> root@atlxx000001:~/src/duo_unix-duo_unix-1.11.4# ./configure --with-pam
> checking for a BSD-compatible install... /usr/bin/ginstall -c
> checking whether build environment is sane... yes
> checking for a thread-safe mkdir -p... /usr/bin/gmkdir -p
> checking for gawk... gawk
> checking whether make sets $(MAKE)... yes
> checking whether make supports nested variables... yes
> checking whether to enable maintainer-specific portions of Makefiles... no
> checking build system type... x86_64-pc-solaris2.11
> checking host system type... x86_64-pc-solaris2.11
> configure: autobuild project... duo_unix
> configure: autobuild revision... 1.11.4
> configure: autobuild hostname... atlxx000001
> configure: autobuild timestamp... 20201221T184806Z
> checking whether make supports the include directive... yes (GNU style)
> checking for gcc... gcc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables...
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... none needed
> checking whether gcc understands -c and -o together... yes
> checking dependency style of gcc... gcc3
> checking how to run the C preprocessor... gcc -E
> checking for grep that handles long lines and -e... /usr/bin/ggrep
> checking for egrep... /usr/bin/ggrep -E
> checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> checking minix/config.h usability... no
> checking minix/config.h presence... no
> checking for minix/config.h... no
> checking whether it is safe to define __EXTENSIONS__... yes
> checking for gcc... (cached) gcc
> checking whether we are using the GNU C compiler... (cached) yes
> checking whether gcc accepts -g... (cached) yes
> checking for gcc option to accept ISO C89... (cached) none needed
> checking whether gcc understands -c and -o together... (cached) yes
> checking dependency style of gcc... (cached) gcc3
> checking how to print strings... print -r
> checking for a sed that does not truncate output... /usr/bin/gsed
> checking for fgrep... /usr/bin/ggrep -F
> checking for ld used by gcc... /usr/bin/ld
> checking if the linker (/usr/bin/ld) is GNU ld... no
> checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -p
> checking the name lister (/usr/bin/nm -p) interface... BSD nm
> checking whether ln -s works... yes
> checking the maximum length of command line arguments... 1572480
> checking how to convert x86_64-pc-solaris2.11 file names to x86_64-pc-solaris2.11 format... func_convert_file_noop
> checking how to convert x86_64-pc-solaris2.11 file names to toolchain format... func_convert_file_noop
> checking for /usr/bin/ld option to reload object files... -r
> checking for objdump... no
> checking how to recognize dependent libraries... pass_all
> checking for dlltool... no
> checking how to associate runtime and link libraries... print -r --
> checking for ar... ar
> checking for archiver @FILE support... no
> checking for strip... strip
> checking for ranlib... ranlib
> checking command to parse /usr/bin/nm -p output from gcc object... failed
> checking for sysroot... no
> checking for a working dd... /usr/bin/dd
> checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
> checking for mt... mt
> checking if mt is a manifest tool... no
> checking for dlfcn.h... yes
> checking for objdir... .libs
> checking if gcc supports -fno-rtti -fno-exceptions... no
> checking for gcc option to produce PIC... -fPIC -DPIC
> checking if gcc PIC flag -fPIC -DPIC works... yes
> checking if gcc static flag -static works... no
> checking if gcc supports -c -o file.o... yes
> checking if gcc supports -c -o file.o... (cached) yes
> checking whether the gcc linker (/usr/bin/ld -64) supports shared libraries... yes
> checking whether -lc should be explicitly linked in... no
> checking dynamic linker characteristics... solaris2.11 ld.so
> checking how to hardcode library paths into programs... immediate
> checking whether stripping libraries is possible... no
> checking if libtool supports shared libraries... yes
> checking whether to build shared libraries... yes
> checking whether to build static libraries... yes
> configure: Adding gcc options: -g -O2 -Wall -D_FORTIFY_SOURCE=2
> checking if -fstack-protector and -fstack-protector-all are supported.... yes
> configure: -fstack-protector disabled on Solaris
> checking whether byte ordering is bigendian... no
> checking for an ANSI C-conforming const... yes
> checking for int64_t... yes
> checking for ANSI C header files... (cached) yes
> checking for inttypes.h... (cached) yes
> checking limits.h usability... yes
> checking limits.h presence... yes
> checking for limits.h... yes
> checking for memory.h... (cached) yes
> checking for stdint.h... (cached) yes
> checking for stdlib.h... (cached) yes
> checking for string.h... (cached) yes
> checking for unistd.h... (cached) yes
> checking for pkg-config... /usr/bin/pkg-config
> checking whether compiling and linking against OpenSSL works... yes
> checking whether X509_TEA_set_state runs... no
> checking security/pam_appl.h usability... yes
> checking security/pam_appl.h presence... yes
> checking for security/pam_appl.h... yes
> checking for security/pam_modules.h... yes
> checking for security/pam_ext.h... no
> checking for main in -lpam... yes
> configure: PAM installation path /usr/lib/security
> checking for pam_vprompt... no
> configure: Using privilege separation user "sshd"
> configure: Using libdir "${exec_prefix}/lib"
> checking for memcpy... yes
> checking for memset... yes
> checking for sysconf... yes
> checking for getaddrinfo... yes
> checking for open64... no
> checking for fopen64... no
> checking for explicit_bzero... yes
> checking for memset_s... yes
> checking for asprintf... yes
> checking for getgrouplist... yes
> checking for strlcpy... yes
> checking for vsyslog... yes
> checking for library containing inet_ntoa... none required
> checking for library containing socket... none required
> checking that generated files are newer than configure... done
> configure: creating ./config.status
> config.status: creating Makefile
> config.status: creating compat/Makefile
> config.status: creating duo_unix_support/Makefile
> config.status: creating lib/Makefile
> config.status: creating lib/libduo.pc
> config.status: creating login_duo/Makefile
> config.status: creating pam_duo/Makefile
> config.status: creating tests/Makefile
> config.status: creating tests/unity_tests/Makefile
> config.status: creating tests/unity_tests/Unity-2.4.3/Makefile
> config.status: creating config.h
> config.status: executing depfiles commands
> config.status: executing libtool commands

## Make failure

> root@atlxx000001:~/src/duo_unix-duo_unix-1.11.4# cd pam_duo/
> root@atlxx000001:~/src/duo_unix-duo_unix-1.11.4/pam_duo# make
> /bin/sh ../libtool  --tag=CC    --mode=link gcc  -g -O2 -Wall -D_FORTIFY_SOURCE=2   -module -no-undefined -avoid-version -shared -export-symbols-regex '^pam_sm_' -o pam_duo.la -rpath /usr/lib/security pam_duo.lo pam_extra.lo pam_duo_private.lo ../lib/libduo.la ../compat/libcompat.la  -lssl -lcrypto -lpam
> libtool: link: /usr/bin/nm -p  .libs/pam_duo.o .libs/pam_extra.o .libs/pam_duo_private.o   ../lib/.libs/libduo.a ../compat/.libs/libcompat.a |  | /usr/bin/gsed 's/.* //' | sort | uniq > .libs/pam_duo.exp
> ../libtool[1718]: eval: syntax error at line 1: `|' unexpected
> *** Error code 3
> make: Fatal error: Command failed for target `pam_duo.la'

**Comment by aaronwmorris** [comment]
I think the problem happens before the `gsed` command.  There are two consecutive pipes, but no command in between.

**Comment by DuoKristina** [comment]
You're correct, there should be a command there. On Solaris systems this may happen if the wrong nm is used. Duo Unix needs the the gnu nm, not the Sun nm at /usr/bin/nm. Does /usr/gnu/bin/nm exist? You may need to install it if it does not, and once present set your path so it has precedence over the Solaris nm. There are some instructions for that [here:](https://help.duo.com/s/article/3970).

**Comment by aaronwmorris** [comment]
Indeed.  Adding /usr/gnu/bin/ to my $PATH corrected my issue.  Thank you!
