### ISSUE TITLE
missing tag 1.11.5

### ISSUE THREAD

**Issue by jafferli** [duosecurity/duo_unix#212]
## Summary
as document mentioned in official release https://duo.com/docs/duounix-notes, there is version 1.11.5 which is available on github repo here. But when I look into the tag, it's stop at 1.11.4.

## Steps to reproduce
1. click https://duo.com/docs/duounix-notes
2. compare with https://github.com/duosecurity/duo_unix/tags, missing 1.11.5

this seems a simple missing tag.

**Comment by mbish** [comment]
This tag is now created https://github.com/duosecurity/duo_unix/releases/tag/duo_unix-1.11.5
Thanks again for pointing this out.
