### ISSUE TITLE
App is blank with two step authentication turned on.

### ISSUE THREAD

**Issue by Aarchie022889** [duosecurity/duo_unix#214]
App is blank with two step authentication turned on. 

Screen shot: http://cl.ly/ViPJ

__Originally posted by @edheltzel in https://github.com/philipheinser/DigitalOcean-Manager/issues/6__

**Comment by DuoKristina** [comment]
Do you have more information? What app? Screen shot isn't viewable.

**Comment by AaronAtDuo** [comment]
This repo has nothing to to with https://github.com/philipheinser/DigitalOcean-Manager
