### ISSUE TITLE
Critical Vulnerability: Default Configuration Can Leave Unenrolled Accounts (Including 'root') Exposed

### ISSUE THREAD

**Issue by DabeDotCom** [duosecurity/duo_unix#219]
## Summary
I have a feeling this is somewhat related to [#102 Return different PAM error codes](https://github.com/duosecurity/duo_unix/issues/102), but I was rather [astonished](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) to discover that, using the CentOS 7 configuration from the [`pam_duo` documentation](https://duo.com/docs/duounix), a New User Policy of `Allow access without 2FA` literally meant, ***ALLOW ACCESS*** — to **any** account that isn't enrolled — i.e., `ssh root@server-01` didn't even prompt me for a password!  😳

### /etc/pam_duo.conf
```
[duo]
ikey = INTEGRATION_KEY
skey = SECRET_KEY
host = API_HOSTNAME
autopush=yes
prompts=1
```

### /etc/ssh/sshd_config
```
PubkeyAuthentication yes
PasswordAuthentication no
AuthenticationMethods publickey,keyboard-interactive

UsePAM yes
ChallengeResponseAuthentication yes
UseDNS no
```

### /etc/pam.d/sshd
```
auth       required     pam_sepermit.so
auth       required     pam_env.so
auth       sufficient   pam_duo.so
auth       required     pam_deny.so
```

### /etc/pam.d/system-auth
```
auth        required      pam_faildelay.so delay=2000000
auth        requisite     pam_unix.so nullok try_first_pass
auth        sufficient    pam_duo.so
```

I'm certainly no expert on the nuanced interplay between PAM and the SSH daemon, but it seems to me that non-enrolled accounts ought to be able to return some kind of `DUNNO` status that instructs the server to fall-through to the next authentication mechanism in the stack.

(PS: Maybe the short answer is simply to add a warning to the documentation, but the way it's listed now seems like a foot-gun just waiting to go off...  «yikes»)

Anyway, the best workaround *I've* been able to come up with thus far is:
```
PubkeyAuthentication yes
PasswordAuthentication yes
#AuthenticationMethods publickey,keyboard-interactive

UsePAM yes
ChallengeResponseAuthentication yes
```

which (unless preempted by a public key) prompts for a password first, 100% of the time, and then adds `pam_duo` as a truly **2nd** factor for enrolled accounts; it's more of a *belt-and-suspenders* approach, rather than an *either-or* alternative.

# Details
- CentOS Linux release 7.9.2009 (Core)
- openssh-server-7.4p1-22.el7_9.x86_64
- openssh-7.4p1-22.el7_9.x86_64
- libssh2-1.8.0-4.el7.x86_64
- duo_unix-1.12.0-0.el7.x86_64

**Comment by DuoKristina** [comment]
The behavior of the new user access policy that you describe is documented here: https://duo.com/docs/policy#new-user-policy.

At the default setting of "Require enrollment", our service would have returned an enrollment message for the unenrolled user, preventing auth completion. It's a good idea to read through the outcomes of different new user policy settings before changing from default, especially if selecting "Allow access without 2FA".

**Comment by DabeDotCom** [comment]
Thanks for the prompt reply Kristina!

> The behavior of the new user access policy that you describe is documented here: https://duo.com/docs/policy#new-user-policy.

Perhaps "Critical Vulnerability" was a bit harsh, but like I say, I was pretty shocked how easy it was for me to end up in a situation where `ssh root@server-01` "Just Worked".

I don't know if you have control over the docs and/or webapp panels, but maybe a simple, amber-colored alert that said something like, "Note: Setting this means **all** attempts to log into unenrolled user accounts will succeed, possibly bypassing additional security restrictions.  See the [New User Policy](https://duo.com/docs/policy#new-user-policy) documentation for more details." would at least suffice to raise a flag for unsuspecting sysadmins to alert them of the potential security risk.  «shrug»

> At the default setting of "Require enrollment", our service would have returned an enrollment message for the unenrolled user, preventing auth completion. It's a good idea to read through the outcomes of different new user policy settings before changing from default, especially if selecting "Allow access without 2FA".

So yeah, I *understand* what's going on; it just feels like a bouncer at a club: if you're on his list, you need an ID, but if you claim to be the President of the USA, and the President of the USA isn't on his list, he'll happily tell everybody, "Yup, he's President of the USA!"

> Am I misunderstanding that the policy was intentionally set to allow access without 2FA?

Basically, our goal is to employ 2FA for administrators, but transparently fall back to password-based authentication for everybody else...  When I tried either `Require Enrollment` (which we don't want to have to put them through) or `Deny Access`, it wouldn't allow me to enter a password at ***all***...

```
ChallengeResponseAuthentiation yes
```

printed:

`Please enroll at https://api-XXX.duosecurity.com/portal?code=CODE&akey=AKEY`    # Require Enrollment
`Access is not allowed because you are not enrolled in Duo. Please contact your organization's IT help desk.`    # Deny Access

But then every subsequent password attempt just returned `Permission denied, please try again.`

```
ChallengeResponseAuthentication no
```

basically did the same, but without the error messages.

Accounts like `root` seem especially pernicious, because there are a small handful of people who, in the middle of the night, might actually need to log in that way, depending on who's on duty...

Is the "Best Practice" to enroll `root` as a "User" and add each person's phone?  That could work, but it seems like it would run afoul of `autopush` — unless there's a way to enable autopush on an account-by-account (and/or user-by-user) basis...  «hmmm»

---
### Another Alternative 

I've discovered I can get 97% of what I want by setting:

- [x] New User Policy: `Deny Access`
- [x] `ChallengeResponseAuthentication yes`
- [x] And adding `auth  sufficient  pam_unix.so nullok try_first_pass` after the `pam_duo` entry in `/etc/pam.d/sshd`

My 3% "Nice-To-Haves" would be:

- [ ] The ability to silence the `Access is not allowed because you are not enrolled...` message — perhaps with a `quiet` argument at the end of the `pam_duo.so` line?  (I ought to be able to patch/PR that pretty easily...)
- [ ] Personally, I'd rather have SSH's more verbose `user@server-01's password:` prompt over pam_unix.so's more spartan `Password:` but "Meh."
- [ ] And of course, we *ALL* wish it could display the `Autopushing login request to phone...` message immediately, but I understand that's likely out of your-all's hands. (#73)

Thanks again!  :-D

**Comment by DuoKristina** [comment]
Thanks for your detailed response. I do have control over some of the things you mention (warnings), and will pass on the other feedback.

>Basically, our goal is to employ 2FA for administrators, but transparently fall back to password-based authentication for everybody else... 

Another idea is to use the [groups](https://duo.com/docs/duounix/#:~:text=XXXXXXXX.duosecurity.com-,groups,-Optional) config option to include admins/exclude users.

I am going to close this issue though, as it isn't a vulnerability or problem with the application per se. When we see someone say "Critical Vulnerability" we definitely take the report seriously.

Thanks for using Duo!
