### ISSUE TITLE
README should note lib paths for 32-bit vs 64-bit

### ISSUE THREAD

**Issue by jaearick** [duosecurity/duo_unix#22]
On both Centos/Redhat 64-bit and SLES 64-bit, I started with a default "/configure --prefix=/usr" and the libduo and pkgconfig stuff ended up being installed in /usr/lib -- and login_duo ended up with a missing shared library at runtime.  When I changed the configure to "./configure --prefix=/usr --libdir=/usr/lib64" then things worked.  The README file should say a few words about this.

**Comment by nathantsoi** [comment]
any updates? i have the same issue on centos 6

```
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I autotools
configure.ac:6: error: Autoconf version 2.65 or higher is required
configure.ac:6: the top level
autom4te: /usr/bin/m4 failed with exit status: 63
aclocal: autom4te failed with exit status: 63
autoreconf: aclocal failed with exit status: 63
```

**Comment by BradleyHiggins** [comment]
Hi Nathan,
  Your issue looks like a different issue than the original post.  It appears that you are trying to run the bootstrap script included in the duo_unix repo, but are encountering an error with regard to your installed version of autoconf.  You'll need to install a later version of autoconf than you get by default on centos 6 to bootstrap duo_unix.  Luckily, you can skip this step entirely by downloading duo_unix from Duo's download site at https://dl.duosecurity.com/duo_unix-latest.tar.gz, and validating its checksum at https://www.duosecurity.com/docs/checksums#duounix.

See https://www.duosecurity.com/docs/duounix for instructions on how to download, build and install duo_unix.

If you have further issues, please open a new issue thread.  Thanks for using Duo!

**Comment by nathantsoi** [comment]
Yep, sadly centos ships with old autoconf. I was about to build autoconf
from source, glad that I dont have to do that...

Happy to use the tar, but is the github repo not up to date? My chef recipe
clones this repo: https://github.com/nathantsoi/chef-duo
