### ISSUE TITLE
RHEL 9 / Centos 9 are missing in repo

### ISSUE THREAD

**Issue by rodehoed** [duosecurity/duo_unix#221]
## Summary
Right now the latest version in the yum repo is el8. EL9 (or Centos 9 stream as you wish) are missing. And yes I do know EL9 is beta atm. but why wait till the GA version? And Centos 9 is GA anyways.

## Workaround

The duo_unix el8 rpm depends on OpenSSL 1.1.1 and EL9 comes with OpenSSL 3. As a result the rpm from el8 can be installed on el9, but cannot find shared openssl libs. This can be fixed by installing compat-openssl11. With login_duo it seems to work flawless. 
I did not test pam_duo.

## Specs
- OS version (ie CENTOS 7 or Ubuntu 14): RHEL 9 Beta / Centos Stream 9
- OS arch (ie 32 or 64):  64
- Using pam_duo or login_duo: login_duo

**Comment by mbish** [comment]
Thanks for taking a look at this. We'll do some internal testing over the next couple of weeks and if this is straightforward then we should get something out in the next release. Otherwise we may choose to wait for GA.

Thanks again for your interest in Duo Unix
