### ISSUE TITLE
enhancement request: syslog the login method

### ISSUE THREAD

**Issue by jaearick** [duosecurity/duo_unix#23]
In the syslog output for login_duo or pam, I would like to know the method used for either success or failure, ie "Push", "Phone", or "SMS", with syslog output like:

login_duo: Successful Duo login via Push for 'joeblow' from '1.2.3.4'

or

sshd[2349]: Successful Duo login via SMS for 'joeblow' from 'somewhere.com'

Would this be possible in the next release please?

**Comment by AaronAtDuo** [comment]
Closing out this old issue
