### ISSUE TITLE
Are there any tips as to how to get NetDrive or SSHFS to work with pam_duo?

### ISSUE THREAD

**Issue by brianlayman** [duosecurity/duo_unix#230]
## Summary
I'd love to retain the workflow I have with every other SSH server, however SSHFS and other seem to break when using the auto push notification.

## Steps to reproduce
1. Try to map a drive letter to an SFTP connection

## Specs
- OS version (ie CENTOS 7 or Ubuntu 14): Ubuntu 20.04
- OS arch (ie 32 or 64): 64
- Using pam_duo or login_duo: pam_duo
- Client OS: Windows 10 64bit

Is there a working method to get a drive letter assigned to the sftp connection that supports 2fa?

The tools I've tried don't work. From the premium NetDrive 2 and 3 (I've not tried sftpdrive) to the open source ( WinFS/SSHFS-Win/SSHFS-Win Manager @ https://github.com/billziss-gh/sshfs-win ).
Does anyone have an alternative working solution or any tips?

It's not the end of the world, I just would like to use the suite of tools I use with all other clients with this client too.

See also: https://support.bdrive.com/t/can-netdrive-work-with-duo-unix-pam-duo/209989
               https://github.com/winfsp/winfsp/discussions/432

**Comment by AaronAtDuo** [comment]
It doesn't look like anyone has suggestions, so closing this.

**Comment by brianlayman** [comment]
ExpanDrive worked for this use case. It handles the prompt well. You hit approve on your phone and the log in completes. Sometimes you will get prompts in the middle of the day if ExpanDrive needs to reconnect due to a time out or something.  That was worrying the first time it happened and I was AFK, but it was easy to confirm that is what happened.
