### ISSUE TITLE
login_duo: no selection output and automatically pushes to first phone in list with eternal terminal

### ISSUE THREAD

**Issue by jshort** [duosecurity/duo_unix#235]
## Summary
If I ssh to a host with duo enabled, I get the selection screen to enter a passcode or select a device to send a push notification.  If I use eternal terminal (which uses ssh) to the same host, I get no stdout and instead, it sends the push notification to the first device in the list and proceeds to authenticate successfully.  Even in that et session, if I run /opt/duo/sbin/login_duo, I get the same behavior.  In a local terminal on the server or in a pure ssh session, this is not the case (I get the output to select option).

## Steps to reproduce
1. et desktop --macserver
2. no output from login_duo but it sends automatic push notification to the first device in list.

## Specs
- OS version (ie CENTOS 7 or Ubuntu 14): Client: MacOS Monterey, Server: MacOS Monterey
- OS arch (ie 32 or 64): 64
- Using pam_duo or login_duo: login_duo

My guess it is an environment issue or something. 

EDIT: Ahh, looks like the shell with eternal terminal is not a login shell, but with pure ssh, it is a login shell so maybe that is it? 

EDIT2: Nm, on my et sessions to linux (Centos) servers, they are not login shells either and yet login_duo still prompts with the option screen so it must be something else.

EDIT3: Hmmm https://github.com/duosecurity/duo_unix/blob/master/login_duo/login_duo.c#L200.  In my linux et sessions, SSH_ORIGINAL_COMMAND is not set, but it is in my MacOS et session so maybe this is it?

**Comment by AaronAtDuo** [comment]
This seems like you're triggering the "if we don't think we can show a prompt let's behave like autopush" logic in https://github.com/duosecurity/duo_unix/blob/6c1abc27390cc4461757cf494e1cb1357e245412/login_duo/login_duo.c#L263.  So I think you're on the right track.  I'm not immediately clear if there's anything we can do about it though...

**Comment by jshort** [comment]
@AaronAtDuo Yeah I am increasingly assuming it is eternal terminal and not login_duo!  Thanks for looking!
