### ISSUE TITLE
Minor improvement to pam_duo syslogging

### ISSUE THREAD

**Issue by jaearick** [duosecurity/duo_unix#25]
Please consider the following changes to syslogging in pam_duo.c:

i: diff -c pam_duo.c.orig pam_duo.c
*** pam_duo.c.orig	Mon Jun 25 11:06:09 2012
--- pam_duo.c	Mon Jun 25 11:07:12 2012
***************
*** 326,332 ****
  		code = duo_login(duo, user, ip, flags,
                      cfg.pushinfo ? cmd : NULL);
  		if (code == DUO_FAIL) {
! 			_log(LOG_WARNING, "Failed Duo login",
  			    user, ip, duo_geterr(duo));
  			if ((flags & DUO_FLAG_SYNC) == 0) {
  				pam_info(pamh, "%s", "");
--- 326,332 ----
  		code = duo_login(duo, user, ip, flags,
                      cfg.pushinfo ? cmd : NULL);
  		if (code == DUO_FAIL) {
! 			_log(LOG_WARNING, "Failed PAM Duo login",
  			    user, ip, duo_geterr(duo));
  			if ((flags & DUO_FLAG_SYNC) == 0) {
  				pam_info(pamh, "%s", "");
***************
*** 337,361 ****
  		/* Terminal conditions */
  		if (code == DUO_OK) {
  			if ((p = duo_geterr(duo)) != NULL) {
! 				_log(LOG_WARNING, "Skipped Duo login",
  				    user, ip, p);
  			} else {
! 				_log(LOG_INFO, "Successful Duo login",
  				    user, ip, NULL);
  			}
  			pam_err = PAM_SUCCESS;
  		} else if (code == DUO_ABORT) {
! 			_log(LOG_WARNING, "Aborted Duo login",
  			    user, ip, duo_geterr(duo));
  			pam_err = PAM_ABORT;
  		} else if (cfg.failmode == DUO_FAIL_SAFE &&
                      (code == DUO_CONN_ERROR ||
                       code == DUO_CLIENT_ERROR || code == DUO_SERVER_ERROR)) {
! 			_log(LOG_WARNING, "Failsafe Duo login",
  			    user, ip, duo_geterr(duo));
  			pam_err = PAM_SUCCESS;
  		} else {
! 			_log(LOG_ERR, "Error in Duo login",
  			    user, ip, duo_geterr(duo));
  			pam_err = PAM_SERVICE_ERR;
  		}
--- 337,361 ----
  		/* Terminal conditions */
  		if (code == DUO_OK) {
  			if ((p = duo_geterr(duo)) != NULL) {
! 				_log(LOG_WARNING, "Skipped PAM Duo login",
  				    user, ip, p);
  			} else {
! 				_log(LOG_INFO, "Successful PAM Duo login",
  				    user, ip, NULL);
  			}
  			pam_err = PAM_SUCCESS;
  		} else if (code == DUO_ABORT) {
! 			_log(LOG_WARNING, "Aborted PAM Duo login",
  			    user, ip, duo_geterr(duo));
  			pam_err = PAM_ABORT;
  		} else if (cfg.failmode == DUO_FAIL_SAFE &&
                      (code == DUO_CONN_ERROR ||
                       code == DUO_CLIENT_ERROR || code == DUO_SERVER_ERROR)) {
! 			_log(LOG_WARNING, "Failsafe PAM Duo login",
  			    user, ip, duo_geterr(duo));
  			pam_err = PAM_SUCCESS;
  		} else {
! 			_log(LOG_ERR, "Error in PAM Duo login",
  			    user, ip, duo_geterr(duo));
  			pam_err = PAM_SERVICE_ERR;
  		}

All I did was add "PAM" before "Duo login" in the syslog messages.  This tells me that pam_duo was used as the authentication method instead of login_duo.  I am testing both and I don't want to guess as to which got used.

The change above also impacts the tests/pam_duo-[1-4].t files, which have to be changed like so:

i: diff -c pam_duo-1.t.orig pam_duo-1.t
*** pam_duo-1.t.orig	Mon Jun 25 11:11:50 2012
--- pam_duo-1.t	Mon Jun 25 11:11:59 2012
***************
*** 1,7 ****
  mockduo down
  
    $ ${TESTDIR}/testpam.py -d -c ${TESTDIR}/confs/duo.conf -f whatever true
!   [4] Failsafe Duo login for 'whatever': Couldn't connect to localhost:4443: Connection refused
    
  down and fail secure
    $ ${TESTDIR}/testpam.py -d -c ${TESTDIR}/confs/mockduo_failsecure.conf -f whatever true
--- 1,7 ----
  mockduo down
  
    $ ${TESTDIR}/testpam.py -d -c ${TESTDIR}/confs/duo.conf -f whatever true
!   [4] Failsafe PAM Duo login for 'whatever': Couldn't connect to localhost:4443: Connection refused
    
  down and fail secure
    $ ${TESTDIR}/testpam.py -d -c ${TESTDIR}/confs/mockduo_failsecure.conf -f whatever true

I did the mods about against files from duosecurity-duo_unix-4c396e7, aka "pre-release 1.9".  Thanks.

**Comment by mschwager** [comment]
This is very old, but thanks for the raising the issue! I'm sure much has changed in the codebase, but if you'd still like this functionality could you submit a PR?

Thanks for using Duo!
