### ISSUE TITLE
drop privileges more thoroughly

### ISSUE THREAD

**Issue by thejh** [duosecurity/duo_unix#28]
`drop_privs` only drops uid and gid, but not supplementary group IDs, I think. If I read the code correctly, this means that code might be running in the context of the `DUO_PRIVSEP_USER` with supplementary groups that grant access to critical areas of the system. (Maybe even to `sudo` if the user is in the `wheel` group or so? I have no idea whether `sudo` just checks the gids of a process or also checks whether the user is a member of the group...)

How about adding a line like this to the unprivileged auth child?

```
if (setgroups(0, NULL)) { die(...); }
```

**Comment by AaronAtDuo** [comment]
Closing out this old issue
