### ISSUE TITLE
Offering... RC script for user-level two factor auth

### ISSUE THREAD

**Issue by shinji257** [duosecurity/duo_unix#38]
This is a small script I wrote real quick to force two factor auth on systems that you don't have root access on.  It doesn't rely on the mechanism from authorized_keys.  This is done for 2 reasons.

1) I wanted two factor to kick in no matter what.  Authorized_keys file only works when using a private key.
2) The command defined in authorized_keys can be overridden with a command specified from ssh when you connect.

Instead I take advantage of the file rc in the same folder.  This file is ran right before the login shell is loaded.  It also happens to run before any forced commands from the ssh command that the user loaded so it can't be bypassed easily.  Last but not least it doesn't rely on the usage of private keys so it works on any login attempt.

Save the following in $HOME/.ssh/rc

```
$HOME/sbin/login_duo -c $HOME/etc/duo/login_duo.conf
if [ $? -ne 0 ] ; then echo "You are not authorized! Bye Bye!"; pkill -SIGHUP -t $SSH_TTY; fi
```

The first line just calls login_duo.  Uses the config from the home folder.
The second line is a typical conditional.  I don't know all the exit codes.  Only tested for a typical approve/deny scenario.  A non-zero exit code means that it wasn't approved so it echos a message and kills the session.  This script does rely on pkill to be available which should be on most systems but if it doesn't you will have to substitute it.  $SSH_TTY gets set to the current login terminal even before the shell kicks in.  I tested this on NetBSD.  And yes while I mention that Duo Security actually works on NetBSD as well.

Environment available before the login shell.
HOME, IFS, LOGNAME, MAIL, OPTIND, PATH, PS1, PS2, PS4, PWD, SHELL, SHLVL, SSH_CLIENT, SSH_CONNECTION, SSH_TTY, TERM, USER

The actual list might vary a bit for you but it should be similar.

**Comment by doublerebel** [comment]
Great script!  Definitely should be in the docs.

This script also runs when `scp` connects, however during `scp` there is no `tty` available and `pkill` throws an error.  Best to add a check to prevent the error.  Here is an example of a SmartOS version:
```sh
TTY=${SSH_TTY:4}
/opt/local/sbin/login_duo
if [ $? -ne 0 ] ; then echo "You are not authorized! Bye Bye!";
  if [[ $TTY != "" ]]; then pkill -HUP -t $TTY; fi
fi
```

**Comment by shinji257** [comment]
Interesting observation however given that it also means that it won't kill the session for scp at all.  We would need to identify a different way to cut off the session in the event it is denied by login_duo otherwise it will connect regardless of if it is approved or denied.

Just for the heck of it I checked sftp and it has a TTY generated but when I checked scp it didn't so that is weird or maybe that is expected behavior.  Either way I don't think there is an effective way to terminate the session at this point which makes duo quite ineffective for scp transfers.

```if [ ! -z $SSH_TTY ] ; then $HOME/sbin/login_duo -c $HOME/etc/duo/login_duo.conf; if [ $? -ne 0 ] ; then echo "You are not authorized! Bye Bye!"; pkill -SIGHUP -t $SSH_TTY; fi; fi```

The above is a one liner now... It is wrapped in a if statement to check for a non-zero SSH_TTY variable before executing so it will skip it on any session that has no tty allocated and silence the error.  If someone can figure out how to kill the session when a tty is not allocated then feel free to provide input on that front as I'd be interested as well.

**Comment by doublerebel** [comment]
@shinji257 On SmartOS (Joyent), my updated script does terminate the scp session if I deny the request through Duo.  What platform/OS are you testing with?

**Comment by shinji257** [comment]
@doublerebel Well it would of been NetBSD but I have not had it setup on that server for a long time.  From what I remembered login_duo just exited with a return value to be checked.  Maybe scp is handling this directly and closing the session?
