### ISSUE TITLE
Bypass Duo Security if authentication is local

### ISSUE THREAD

**Issue by shinji257** [duosecurity/duo_unix#39]
This is more of a ticket that is informational here but if anyone has any input to the security implications let me know.

I have a VPS that I manage remote.  My host gives me console access which appears as a local connection when I use it.  I also have SSH.  When I implemented Duo Unix 2 things kinda got to me.

1) I had to go through two factor every time I ran sudo
2) I had to do the same regardless if I authenticated locally or remote.  Even as root.

I know the first is being addressed via another ticket but the second I wanted to take care of.

I did some digging and kinda figured out how pam_access works and after managing to lock myself out twice (thank goodness for host rescue mode) I got it figured out.

This is for Ubuntu 12.04.3 but you can probably apply it elsewhere.  It is very important that you already have a root session active and do not close it until you test your changes otherwise you might lock yourself out.  It is also recommended to temporarily secure another way of getting to the server configuration files (editing them) in case you do manage to lock yourself out like I did.

Pam common-auth as per the documentation

```
# here are the per-package modules (the "Primary" block)
auth    requisite                       pam_unix.so nullok_secure
# Duo Security
auth    [success=1 default=ignore]      pam_duo.so
# here's the fallback if no module succeeds
auth    requisite                       pam_deny.so
```

Now I add "auth    [success=2 default=ignore]      pam_access.so accessfile=/etc/security/access-local.conf" right before the pam_duo line.

```
# here are the per-package modules (the "Primary" block)
auth    requisite                       pam_unix.so nullok_secure
# Duo Security -- set to skip if auth is local
auth    [success=2 default=ignore]      pam_access.so accessfile=/etc/security/access-local.conf
auth    [success=1 default=ignore]      pam_duo.so
# here's the fallback if no module succeeds
auth    requisite                       pam_deny.so
```

success=2 means to skip the next 2 lines if succeed.  

Contents of access-local.conf

```
+ : ALL : LOCAL
- : ALL : ALL
```

Note: This bypasses it on sudo as well as local console.  This is because sudo appears to be a local connection just like console.

**Comment by lrhazi** [comment]
Is there a way to bypass 2FA only for specific local users and not all local users?

**Comment by AaronAtDuo** [comment]
@lrhazi The two ideas that come to mind are either some _really_ creative PAM configuration or using groups.

(for more info on how to bypass groups see https://duo.com/docs/duounix#duo-configuration-options)
