### ISSUE TITLE
va_copy

### ISSUE THREAD

**Issue by mwarner1** [duosecurity/duo_unix#56]
When compiling duo_unix under Solaris 10 with the Solaris Studio compiler on amd64, a line needs to be changed. Samba had the same issue as reported at https://bugzilla.samba.org/show_bug.cgi?id=3159

#ifndef VA_COPY
#if defined HAVE_VA_COPY || defined va_copy
#define VA_COPY(dest, src) va_copy(dest, src)

This is for version 1.9.13, compat/asprintf.c

**Comment by mschwager** [comment]
I'm going to close this for now. Let me know if you run in to this issue again!
