### ISSUE TITLE
duo_unix on Solaris

### ISSUE THREAD

**Issue by mwarner1** [duosecurity/duo_unix#57]
When compiling on Solaris 10/amd64/Solaris Studio compiler, the configure script does not include "-lnsl -lsocket" and both are required to successfully link the binary.

It would be great if configure could do this automatically. As a workaround, simply defining this works:

LIBS="-lnsl -lsocket"

This is against version 1.9.13.

**Comment by mschwager** [comment]
Hey @mwarner1 ! Sorry for the late response! We'll definitely look into this, thanks for the heads up :)

(I'll admit it won't be immediately as our plates are pretty full right now, but we will get around to it)
