### ISSUE TITLE
shared-lib-calls-exit /usr/lib64/libduo.so.3.0.0 exit@GLIBC_2.2.5

### ISSUE THREAD

**Issue by deadpoint** [duosecurity/duo_unix#59]
Hello,

I'm building duo_unix for openSUSE/SLES via the OpenSUSE Build Service and the rpmlint checks which evaluate the packages is throwing the following warning for libduo.so.3.0.0. See the build log for the complete build output.

https://build.opensuse.org/package/live_build_log/home:deadpoint/duo_unix/openSUSE_13.1/x86_64

[   14s] libduo3.x86_64: W: shared-lib-calls-exit /usr/lib64/libduo.so.3.0.0 exit@GLIBC_2.2.5
[   14s] This library package calls exit() or _exit(), probably in a non-fork()
[   14s] context. Doing so from a library is strongly discouraged - when a library
[   14s] function calls exit(), it prevents the calling program from handling the
[   14s] error, reporting it to the user, closing files properly, and cleaning up any
[   14s] state that the program has. It is preferred for the library to return an
[   14s] actual error code and let the calling program decide how to handle the
[   14s] situation.

**Comment by mschwager** [comment]
Thanks for the heads up! I'm going to close this for now, though, since this warning is coming from a third-party library we use, not any code we've written.
