### ISSUE TITLE
missing-call-to-setgroups-before-setuid /usr/sbin/login_duo

### ISSUE THREAD

**Issue by deadpoint** [duosecurity/duo_unix#60]
I'm building duo_unix for openSUSE/SLES via the OpenSUSE Build Service and the rpmlint checks which evaluate the packages is throwing the following warning for /usr/sbin/login_duo. See the link to the build log for the complete build output.

https://build.opensuse.org/package/live_build_log/home:deadpoint/duo_unix/openSUSE_13.1/x86_64

[   14s] duo_unix.x86_64: W: missing-call-to-setgroups-before-setuid /usr/sbin/login_duo
[   14s] This executable is calling setuid and setgid without setgroups or initgroups.
[   14s] There is a high probability this mean it didn't relinquish all groups, and
[   14s] this would be a potential security issue to be fixed. Seek POS36-C on the web
[   14s] for details about the problem.

**Comment by AaronAtDuo** [comment]
Closing out this old issue
