### ISSUE TITLE
Duo unix goes into fail mode without logging anything

### ISSUE THREAD

**Issue by 314159** [duosecurity/duo_unix#66]
Now that I have systems with duo_unix deployed in a production environment and it all works, occasionally when ssh'ing to a server I do not get prompted by duo_unix to authenticate myself but get a shell prompt immediately.

I do have failmode set to "safe" so if there is some problem in the system or network I can still get in.

My problem is that I did not get any message in syslog (or on the screen when I ran duo_unix -d manually) when this problem is happening.  I _assume_ there is some service or network failure happening between my servers and duosecurity, but I do not know that.

Shouldn't all failures be logged?

**Comment by BradleyHiggins** [comment]
Thanks for using Duo!

What version of duo unix are you using? How have you integrated Duo - with ssh or as a pam module? Are you using the 'group' option in your duo configuration?  If you are using the 'group' filter, users not in the specified group will bypass 2fa.

It sounds like you aren't yet positive that the issue you're seeing is failmode related.  If you disable connectivity between your unix host and Duo's service, can you reproduce the behavior?  You can disable connectivity, for instance, by adding your Duo hostname to the loopback IP in your /etc/hosts file.

**Comment by 314159** [comment]
On Jul 21, 2015, at 8:52 AM, BradleyHiggins <notifications@github.com> wrote:

> Thanks for using Duo!
> 
Great product!

> What version of duo unix are you using? How have you integrated Duo - with ssh or as a pam module? Are you using the 'group' option in your duo configuration? If you are using the 'group' filter, users not in the specified group will bypass 2fa.
> 
I am using version 1.9.14 of duo_unix, and I have integrated it using ssh.  I am not using the group option.
> It sounds like you aren't yet positive that the issue you're seeing is failmode related. If you disable connectivity between your unix host and Duo's service, can you reproduce the behavior? You can disable connectivity, for instance, by adding your Duo hostname to the loopback IP in your /etc/hosts file.
> 
Actually, I am pretty sure it is related to failmode because normally I _do_ have duo_login ask me to authenticate, but sometimes it doesn't.  I don't think my internet connectivity is all that bad so I suspect more of an issue elsewhere and I was hoping to find out in syslog _why_ it had to go to "safe" failmode.  After all, I _am_ with ssh coming in that same internet.

**Comment by BradleyHiggins** [comment]
> Actually, I am pretty sure it is related to failmode because normally I _do_ have duo_login ask me to authenticate, but sometimes it doesn't.

I would like to confirm that you're encountering a failmode scenario.  Could you try to reproduce the behavior by disabling the connectivity between your unix host and Duo's servers?  You can disable the connectivity by adding your Duo hostname to the loopback IP in your /etc/hosts file.  Then, run login_duo -d and see whether an error mesage is displayed or not.

>My problem is that I did not get any message in syslog (or on the screen when I ran duo_unix -d manually) ...
>Shouldn't all failures be logged?

When I try this test, I see a message written to the console.  This same message should be written to syslog during a regular, non-debug login scenario.  Please try this, and confirm that you don't see a message reported on your console.

**Comment by 314159** [comment]
I was waiting for this to occur again, but it hasn't.  So I'm going to close this.
