### ISSUE TITLE
Non-interactive ssh sessions and CLI tool creation

### ISSUE THREAD

**Issue by andrewdeandrade** [duosecurity/duo_unix#69]
I'm currently working on an internal CLI tool that will eventually be open-sourced and one issue that I've encountered with Duo unix (and also encountered previously with other terminal 2fa solutions) is an elegant way to spawn non-interactive terminal commands that may require 2fa. 

I'm going to use the tool I'm working on as an example. It performs a bunch of actions on a self-hosted git  server protected by duo_unix. When a user doesn't have an active session and executes a command, the command will basically hang. There are two possible solutions here that I can think of but I want a better user experience. The first solution is to provide the user with instructions on how to put an ~/.autopush file in the home folder for their user on the authentication servers. This signals to duo to use the primary 2fa method for that user. The second approach is to spawn all commands that may require authentication with stdio inherited. This is also problematic for three reasons
- the moment you forward fds 0, 1 and 2 to the child process you lose the ability to intercept and parse the stdout and stderr from that process 
- the user experience for your tool becomes noticeably worse because you expose all the noisy output from your child_process that you may want to suppress. 
- you lose the ability to effectively parallelize tasks since all of them would be inheriting and working with the same file descriptors.

What I'd really like to see is:
- duo_unix detects when it is being run in a non-interactive terminal session and behaves more appropriately (perhaps there is an implicit autopush when detected)
- A way to effectively test tools that have to work with duo_unix. In the course of developing this CLI tool, it was impractical to create the circumstances that lead to the 2fa prompt more than once per day. This meant that it took me a lot longer to test out if any of my hypothesized workarounds worked as desired. The ability to view active sessions and terminate an active session (either via the web or programmatically would be nice for being able to create circumstances where I'll be prompted to log in again.

**Comment by Hashfyre** [comment]
The non-interactive method would also be useful for Continuous Integration scenarios.
Currently we bake all our EC2: AMIs through Wercker, using Packer as a tool within the wercker box. 

However as all provisioning happens through a user account unassociated with a duo identity (not being a person it lacks a phone number to push OTP to), CI bakes broke once we switched from `login_duo` to `pam_duo`. A non interactive implementation would help this scenario.

**Comment by BradleyHiggins** [comment]
@Hashfyre Since you say the user doesn't have a Duo account, it doesn't sound like a non-interactive 2fa wouldn't fix your use case.  Does the 'groups' configuration option help you?  It allows some user accounts to bypass Duo, based on group membership of the account.

**Comment by BradleyHiggins** [comment]
@malandrew Sorry for not responding to your issue, it fell off of our radar.  In the future, please feel free to contact support@duo.com, where we have processes in place to ensure requests are captured and tracked.

Have you tried the 'autopush' configuration feature of duo unix?  It may address your use case.

Thanks for using Duo!

**Comment by AaronAtDuo** [comment]
Closing out this old issue
