### ISSUE TITLE
`login_duo` doesn't work from `/usr/local` on OS X El Capitan

### ISSUE THREAD

**Issue by Noleli** [duosecurity/duo_unix#72]
Because of [System Integrity Protection](https://developer.apple.com/library/mac/documentation/Security/Conceptual/System_Integrity_Protection_Guide/FileSystemProtections/FileSystemProtections.html#//apple_ref/doc/uid/TP40016462-CH2-DontLinkElementID_1) in OS X 10.11, `login_duo` needs to be installed in `/usr/local` instead of `/usr`. Changing the prefix flag on `configure` seems to work: the binary is installed in `/usr/local/bin`, and `libduo` is installed in `/usr/local/lib`.

But when when you try to run it, it says

```
dyld: Library not loaded: /usr/lib/libduo.3.dylib
  Referenced from: /usr/local/sbin/./login_duo
  Reason: image not found
Trace/BPT trap: 5
```

It looks to me like either:

(a) the path to `libduo` is hardcoded somewhere, or
(b) the dynamic linker isn't getting the memo

Relatedly, once this is fixed, the [Duo Unix docs](https://www.duosecurity.com/docs/duounix) should be updated to reflect needing to install in `/usr/local` on OS X.

Thanks!

**Comment by mschwager** [comment]
I'm unable to reproduce locally, but we have a few options for solving the problem.

If you'd just like to get-it-working then this (http://stackoverflow.com/a/17704255) seems like it should be sufficient.

If you'd like to solve the linker issue then I'm going to need more information. When installing with the `--prefix` flag configured you should see something like:

```
Libraries have been installed in:
   /path/to/prefix/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
```

On my system, when running `make`, I see `login_duo` being compiled correctly with `-Wl,-rpath -Wl,/path/to/prefix/lib`, and the binary runs correctly. I'm assuming this isn't the case for you.

Could you post the output of your `./configure`, `make`, and `make install` commands?

Thanks!

**Comment by Noleli** [comment]
Thanks! Using `otool` did the trick. The output of my `configure` and the `Makefile` are at https://gist.github.com/Noleli/0d7ac10b193c1a74cc8f

I guess the main thing is that since it'll have to be installed in `/usr/local` on El Capitan, it'd be nice if it worked "out of the box" by following the directions in the docs.

**Comment by mschwager** [comment]
Hey @Noleli, I was able to reproduce your issue, and the above commit fixed it for me. Can you confirm?
