### ISSUE TITLE
Make accept_env_factor work with PAM

### ISSUE THREAD

**Issue by mfischer-zd** [duosecurity/duo_unix#74]
The `accept_env_factor` option should work with PAM, just like it does with login_duo.

**Comment by mschwager** [comment]
Did you have a fix in mind? Perhaps using `pam_env`?

**Comment by mfischer-zd** [comment]
I'm not sure.  I imagine it depends on when sshd obtains the environment variable from the client.  If it's not available before sshd gets into the PAM auth context, then it's probably impossible.

**Comment by sigmunau** [comment]
Any news on this?There are many reasons to want to use duo_pam over duo_login, but without this we will loose the ability to run scp and other non-interactive tools with ssh

**Comment by PantherJohn** [comment]
@mfischer-zd 
> If it's not available before sshd gets into the PAM auth context, then it's probably impossible.

You can't assume that we only use PAM for `ssh` though. Sometimes it would be useful to integrate PAM with other services such as `apache`.

**Comment by AaronAtDuo** [comment]
Closing out old tickets
