### ISSUE TITLE
Feature request: allow reuse of Duo tokens

### ISSUE THREAD

**Issue by mfischer-zd** [duosecurity/duo_unix#75]
In my shell I override the ssh(8) command with a Bash function that first copies my shell profiles to the target machines using rsync(1)-over-ssh and then executes the actual `ssh` command to log into the remote machine. 

When I log into a Duo-enabled ssh server, this means I get prompted twice to log in each time.  

But as a practical matter, this is not necessary if the token has not rotated between login attempts.

What do you think about the following feature?  (It can be optional, of course.)
- Making pam_duo set the `DUO_TOKEN` environment variable to the most-recently-used token, if good
- Allowing the user to write the token stored in the environment variable to `$HOME/.duo_token` and delete it from her environment
- Making pam_duo attempt to read the token from `$HOME/.duo_token` (after ensuring the file is mode 0600), and, if still good, allowing the user to pass token validation without re-entering the token or pushing to the mobile device

There is a small amount of security risk in storing the token in the user's environment, but since it's rotated every 30 seconds, I think the risk is minimal.

**Comment by mfischer-zd** [comment]
Alternatively, the pam_duo module could cache tokens privately so that they're never exposed to the user's environment, but that is probably a more complicated solution, engineering-wise.

**Comment by mschwager** [comment]
Hey @mfischer-zd! Thanks for all these ideas!

Regarding this particular issue, it seems like a high risk/low reward type scenario with many potential gotchas. We try to avoid maintaining authentication state on the machine insofar as is possible, and we also try to avoid relying on the environment for security reasons.

**Comment by mfischer-zd** [comment]
Can we walk through the scenarios to better gauge the risk?

**Comment by AaronAtDuo** [comment]
Closing out this old issue
