### ISSUE TITLE
SELinux rules don't handle proxies on EL7

### ISSUE THREAD

**Issue by willthelaw** [duosecurity/duo_unix#78]
Hi,

This seems to work on EL6; no clue there.  Sort of related to issue #70.

You need to open a port for the proxy.  I guess, you may ONLY need a port for that proxy? Oh, yeah, that seems to be true.

So for my case, with a proxy on port 8000, I needed this:

```
require {
    type soundd_port_t;
    type sshd_t;
    class tcp_socket name_connect;
};

allow sshd_t soundd_port_t:tcp_socket name_connect;
```

Because in the byzantine world of SELinux soundd_port = port 8000. Your miles will vary dependy, and maybe people should just stick with http_port_t which covers tcp      80, 81, 443, 488, 8008, 8009, 8443, 9000.  Who came up with 9000?  That's no more crazy than 8000.

Hopefully there is a more general way to handle this, or perhaps it just needs to be documented for people trying to use proxies.

**Comment by xdesai** [comment]
Sorry for commenting on such an old issue, but I'm doing a bit of spring cleaning.
We resolved this issue by adding http_cache_port to the SELinux policy. Now users with the latest Duo Unix can use common HTTP Proxy ports and also extend that tag to contain any ports they need.
