### ISSUE TITLE
Integrating with xrdp

### ISSUE THREAD

**Issue by Riz0** [duosecurity/duo_unix#83]
Hi guys,

Every since enabling 2FA with pam_duo, xrdp has troubling logging into a session. I tried to edit the /etc/pam.d/sesman file from:

> @include common-auth
> @include common-account
> @include common-session
> @include common-password

to:

> # @includecommon-auth
> # @include common-account
> # @include common-session
> # @include common-password
> 
> auth  [success=1 default=ignore] pam_duo.so

But it still fails login and nothing is pushed to my phone for authentication. Any idea how to get it working? @akgood @kra @dugsong 

Thanks

**Comment by drewstinnett** [comment]
Hi @riz0, are you still having issues?  We've been using pam_duo successfully with xrdp-0.9.0-4 on RHEL7.  We needed the following in /etc/pam.d/xrdp-sesman
```
auth       requisite     pam_duo.so conf=/etc/duo/xrdp_pam_duo.conf
```

**Comment by andreroland** [comment]
Hi @drewstinnett, I know its been quite a while but Im trying to use XRDP (xrdp-0.9.6-1) on RH 7.4 with duo. Duo seems to be working fine through ssh and GDM but I could not configure PAM for xrdp-sesman. You mentioned you have a valid configuration but /etc/duo/xrdp_pam_duo.conf is nowhere to be found. Could you detail what is in there and how to setup this? BTW, xrdp work fine without duo 2FA.

**Comment by andreroland** [comment]
Hi @drewstinnett I actually tried to play with it. No luck. I cant see the duo verification screen and actually xrdp fails to login... it seems its just looking for user and pwd.

**Comment by hypertoast** [comment]
Sorry to open an old issue. Even I have trouble enabling DUO with XRDP. Any step-by-step tutorial on how to make it work? Thanks

**Comment by andreroland** [comment]
@hypertoast I struggled with it for some time but couldnt make it work. Id appreciate a working setup as well.

**Comment by JerryTraskelin** [comment]
I was also struggling with this, but I was able to get it working. It looks like xrdp is unable to display the menu where you select which authentication method you want to use (push, text, call). Add the following line to your configuration file (/etc/duo/pam_duo.conf for example):
`autopush = yes`

@andreroland @hypertoast

**Comment by MetalJacx** [comment]
When using this with MXLinux. Besides not getting xRDP to work properly. I was also running to a different issue where I couldn't get the package manager to load properly. This was do to me setting duo system wide. Sudo and Su commands wanted Auth everytime time. I change the following two files:
/etc/pam.d/su
/etc/pam.d/sudo

```
#@include common-auth                                                            #hash this line
auth [success=1 default=ignore] pam_unix.so nullok_secure     #
auth requisite pam_deny.so                                                        # Add These three lines to poth files
auth required pam_permit.so                                                      #
```
This not only fix my package issue but fix my xRDP issue. Not sure if this is a security hoel for duo, but i didn't want to have to auth every time I needed to sudo.

**Comment by abhishek0804** [comment]
> Hi @andreroland , The /etc/duo/xrdp_pam_duo.conf was just a slightly modified version of our /etc/duo/pam_duo.conf. You could probably just make that '/etc/duo/pam_duo.conf' instead



> Hi @andreroland , The /etc/duo/xrdp_pam_duo.conf was just a slightly modified version of our /etc/duo/pam_duo.conf. You could probably just make that '/etc/duo/pam_duo.conf' instead

Hi! Can you mention the exact steps that you did to enable xrdp with duo? Im still struggling with it. Any reference documents or links would be helpful

**Comment by abhishek0804** [comment]
> I was also struggling with this, but I was able to get it working. It looks like xrdp is unable to display the menu where you select which authentication method you want to use (push, text, call). Add the following line to your configuration file (/etc/duo/pam_duo.conf for example):
> `autopush = yes`
> 
> @andreroland @hypertoast

Hi! Can you mention the exact steps that you used to get it working from the start?

**Comment by JerryTraskelin** [comment]
@abhishek0804 Just follow the instructions in the official Duo documentation: https://duo.com/docs/duounix and add the line I mentioned to your configuration.

**Comment by abhishek0804** [comment]
> @abhishek0804 Just follow the instructions in the official Duo documentation: https://duo.com/docs/duounix and add the line I mentioned to your configuration.

Any changes in the /etc/pam.d/xrdp-sesman file? Its still using username & password to login and giving no pop ups for the duo passcode

**Comment by JerryTraskelin** [comment]
@abhishek0804 no changes to `xrdp-sesman`. There will be no pop up as xrdp doesn't have the capability to display any pop ups. That's why you need to do what I said in https://github.com/duosecurity/duo_unix/issues/83#issuecomment-416964497

**Comment by andreroland** [comment]
> > @abhishek0804 Just follow the instructions in the official Duo documentation: https://duo.com/docs/duounix and add the line I mentioned to your configuration.
> 
> Any changes in the /etc/pam.d/xrdp-sesman file? Its still using username & password to login and giving no pop ups for the duo passcode

I think @JerryTraskelin comment led me to the right direction. If you use pure VNC you can see the DUO method selection box (push, sms, call) but with XRDP implementation you must (at least in jun/2018) enable autopush. Autopush will send the request to your mobile app without asking it.

**Comment by raidenii** [comment]
Make sure you have enrolled Duo protected app on the phone first (since if not, xrdp would simply fail without prompting). Just set it up for common auth or ssh for enrolling, and then create a `/etc/duo/xrdp_pam_duo.conf`:

```
[duo]
; Duo integration key
ikey = INTEGRATION_KEY
; Duo secret key
skey = SECRET_KEY
; Duo API hostname
host = API_HOSTNAME
; Enable autopush
autopush = yes
; Only allow 1 prompt
prompts = 1
```

And comment `@include common-auth` from `/etc/pam.d/xrdp-sesman`, add this to the bottom:
```
auth requisite pam_duo.so conf=/etc/duo/xrdp_pam_duo.conf
```

Tested working on Debian 10.

**Comment by acascianelli** [comment]
Is there any other options for using Duo with xRDP now?  I got it working by forcing a push to the app, but I would really like to be able to provide a code at the xRDP login screen.

**Comment by mbish** [comment]
In general injecting additional input fields or otherwise getting user input on a simple username/password login form needs to be done on a case-by-case basis as there doesn't exist a standard for augmenting such forms with additional challenge-response flows. 

Since we don't have plans to add support for xRDP specifically, I'm going to close this for now.
