### ISSUE TITLE
Adding to source list on ARM device

### ISSUE THREAD

**Issue by Riz0** [duosecurity/duo_unix#84]
Hi again,

I'm trying to add the duo_unix package source to my source list, I know it doesn't say it's specifically tested against ARM devices but works just fine (on my Rpi). Only problem is doesn't want to play nice with apt-get update, it throws error:

> Unable to find expected entry 'main/binary-armhf/Packages'

I got around the error message by adding "deb [arch=amd64]" to the source list as such:

> deb [arch=amd64] http://pkg.duosecurity.com/Debian jessie main

 but it still can't find the duo_unix package when issuing "apt-get install duo-unix" it returns:

> Unable to locate package duo-unix

Any idea for a workaround till ARM is officially supported? 

@kra @akgood @dugsong 

Thanks

**Comment by BradleyHiggins** [comment]
Hi Riz0,
  We don't make an ARM build of duo_unix available from our prebuilt package list at this time, so you won't be able to install it with your package manager.  Instead, you can download and build duo unix from source for you ARM machine, following the instructions on our website: https://duo.com/docs/duounix

Thanks for using Duo!

**Comment by cmebert** [comment]
Any updates on this?  With the new AWS Graviton processors I imagine there is an ever increasing group of Duo customers wanting to protect their arm64 resources with MFA.

**Comment by xdesai** [comment]
Hey @cmebert at this time we are still recommending that customers install from source on any distros we don't currently have packages built for. It's good to know about AWS graviton though. I personally wasn't aware of that.
I'll pass this ticket in front of our product team, but I also recommend that you reach out to the Duo support team and add yourself onto the feature request for this. It helps us at Duo prioritize what we should work on next.
Thanks!

**Comment by mattlqx** [comment]
Yeah, ARM is going to be (even more of) a major platform in the server space in the coming years. A pre-built package would also be very useful for Raspberry Pis even.
