### ISSUE TITLE
[SELINUX] Duo Pam module is not allowed to connect to HTTPS (RHEL 7)

### ISSUE THREAD

**Issue by rodehoed** [duosecurity/duo_unix#85]
Even with the policy installed the duo_pam will fail to connect to Duo. In the audit log I see:

`type=AVC msg=audit(1467902419.111:92031): avc:  denied  { name_connect } for  pid=21571 comm="login" dest=443 scontext=system_u:system_r:local_login_t:s0-s0:c0.c1023 tcontext=system_u:object_r:http_port_t:s0 tclass=tcp_socket`

**Fix:**
setsebool -P authlogin_yubikey=1

**Comment by agreenbhm** [comment]
Thanks @rodehoed, you're the bomb, totally fixed the issue.  I wasted a lot of time on that this morning.

**Comment by vbscott** [comment]
I am going to close this out.  Feel free to reopen the issue if you have problem with this again.
