### ISSUE TITLE
After sssd auth, gecos not userid being sent to api hostname

### ISSUE THREAD

**Issue by marcurdy** [duosecurity/duo_unix#86]
We're using duo_unix after a successful sssd login to an openIPA server.  For a few months now both in the Ubuntu package and self-compiled,, the new code has failed to work like old versions.  It is sending the getent passwd gecos field instead of the userid.  Docs say the gecos field is an option available to use in the config, but it is flagged as bad and not a default of "no" for me.

The workaround for me is to comment out the section in pam_duo.c starting and ending with:
    /\* Use GECOS field if called for _/
    /_if (cfg.send_gecos) {
      if (strlen(pw->pw_gecos) > 0) {
          user = pw->pw_gecos;
      } else {
          duo_log(LOG_WARNING, "Empty GECOS field", pw->pw_name, NULL, NULL);
      }
    }
   */

**Comment by BradleyHiggins** [comment]
I'm sorry to hear you've been running into some issues with duo_unix.  Could you please verify that you're using the latest version of both libduo.so and pam_duo.so?  The issue you've described could happen if an updated pam_duo.so were linking against an older version of libduo.so.

You can grab the version info from the .so directly with `strings /usr/lib/libduo.so | grep 1\.9`, which should output '1.9.19', and again with `strings /lib64/security/pam_duo.so | grep pam_duo/`, which should output 'pam_duo/1.9.19'.

**Comment by marcurdy** [comment]
root@xxx:~# strings /lib64/security/pam_duo.so | grep pam_duo/
pam_duo/1.9.19

root@xxx:~# strings /usr/lib/libduo.so | grep 1\.9
1.9.19
/duo_unix-1.9.19/lib
/duo_unix-1.9.19/compat

**Comment by BradleyHiggins** [comment]
Thanks for double-checking that.  Could you open a ticket with Duo by contacting support@duo.com?  I'd like to follow-up with you through our regular support channel.  Be sure to include a link to this issue thread when you open the ticket.

Thanks for using Duo!

**Comment by BradleyHiggins** [comment]
Duo unix now (as of 1.9.20) statically links libduo code with pam_duo or login_duo. This will ensure no mismatches between the library versions going forward.
