### ISSUE TITLE
Duo-unix on ubuntu 14.04LTS – Permission denied?

### ISSUE THREAD

**Issue by seapasulli** [duosecurity/duo_unix#89]
Hello all,

I also posted to the duo community forum/discuss board. Sorry if this is not the correct place for my question. I am new and trying to learn. Please let me know and I will move/delete this.

I am trying to set up duo-unix to do 2FA + ssh-key authentication on a linux VM (ubuntu 14.04) as a test. I am using the ubuntu repository supplied in the guide/doc here :: https://duo.com/docs/duounix

My current steps are:
------------------------------------------------------------------------------------------------
    ubuntu@duo2fa-test-free:~$ sudo apt-get install build-essential libss-dev
    ubuntu@duo2fa-test-free:~$ sudo apt-get update && sudo apt-get upgrade -y
    ubuntu@duo2fa-test-free:~$ curl -s https://duo.com/APT-GPG-KEY-DUO | sudo apt-key add - && echo 'deb http://pkg.duosecurity.com/Ubuntu trusty main' | sudo tee /etc/apt/sources.list.d/duosecurity.list
    ubuntu@duo2fa-test-free:~$ sudo apt-get update && sudo apt-get install duo-unix

    ubuntu@duo2fa-test-free:~$ cat <<EOF | sudo tee /etc/duo/duo_login.conf
    ikey = 
    skey = 
    host = 
    groups = users,!root
    failmode = safe
    pushinfo = yes
    http_proxy = http://cloud-proxy:3128/
    autopush = yes
    motd = yes
    prompts = 1
    accept_env_factor = no 
    fallback_local_ip = no
    https_timeout = 0
    EOF

    ubuntu@duo2fa-test-free:~$ /usr/sbin/login_duo 
    Couldn't open /etc/duo/login_duo.conf: Permission denied
------------------------------------------------------------------------------------------------

On top of this my environment seems to be somewhat broken as well::
------------------------------------------------------------------------------------------------
    ubuntu@duo2fa-test-free:~$ exit
    logout
    ubuntu@duo2fa-test-free:~$ exit
    Connection to 172.16.135.16 closed.
    seapasulli@local:~$ ssh -Al ubuntu 172.16.135.16
    Couldn't open /etc/duo/login_duo.conf: Permission denied
------------------------------------------------------------------------------------------------

I have tried this on multiple fresh ubuntu 14.04 vms on digitalocean and on my local laptop with the same result. I have also built from source and again i get permission denied without any form of prompt for an authenticator. 

Is there a way to enforce 2fa for non-root users without locally installing login_duo?

**Comment by xdesai** [comment]
Hi seapasulli,
Our recommended option to use 2FA with ssh-key authentication is to use our pam module instead of login_duo. It sounds like you may not have a specific preference so can I recommend that you try using pam_duo instead? The docs you linked have instructions for editing the pam configuration files and what you'll need to do to have pam_duo set up. From what you've said you should already have the pam module installed.

Also one quick tip, as you're playing around it's probably a good idea to keep a root shell open on your vm so you don't accidentally lock yourself out :) 

Thanks for using Duo and feel free to follow up here with any more questions.

**Comment by seapasulli** [comment]
I've tried using pam_duo as well by doing the following:

    ubuntu@duo2fa-test-free:~$ sed '/motd/d' /etc/duo/login_duo.conf > /etc/duo/pam_duo.conf

editing my ssh config as follows:
    
    root@duo2fa-test-free:/etc/duo# grep -v ^# /etc/ssh/sshd_config | grep -v ^$ 
    Port 22
    Protocol 2
    HostKey /etc/ssh/ssh_host_rsa_key
    HostKey /etc/ssh/ssh_host_dsa_key
    HostKey /etc/ssh/ssh_host_ecdsa_key
    HostKey /etc/ssh/ssh_host_ed25519_key
    UsePrivilegeSeparation yes
    KeyRegenerationInterval 3600
    ServerKeyBits 1024
    SyslogFacility AUTH
    LogLevel INFO
    LoginGraceTime 120
    PermitRootLogin without-password
    StrictModes yes
    RSAAuthentication yes
    PubkeyAuthentication yes
    IgnoreRhosts yes
    RhostsRSAAuthentication no
    HostbasedAuthentication no
    PermitEmptyPasswords no
    AuthenticationMethods publickey,keyboard-interactive
    ChallengeResponseAuthentication yes
    PasswordAuthentication no
    X11Forwarding yes
    X11DisplayOffset 10
    PrintMotd no
    PrintLastLog yes
    TCPKeepAlive yes
    AcceptEnv LANG LC_*
    Subsystem sftp /usr/lib/openssh/sftp-server
    UsePAM yes
    KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
    Ciphers aes256-ctr,blowfish-cbc
    MACs hmac-ripemd160,hmac-sha2-256,hmac-sha2-512
    UseDNS no
    RevokedKeys /usr/local/etc/ssh/krlfile

nd I have commented out `@include common-auth` from /etc/pam.d/sshd and replaced it with the following 4 lines::
    root@duo2fa-test-free:/etc/duo# grep -v ^# /etc/pam.d/sshd | grep -v ^$ | head -n4
    auth  [success=1 default=ignore] /lib64/security/pam_duo.so
    auth  requisite pam_deny.so
    auth  required pam_permit.so
    auth  optional pam_cap.so

I am denied with the following logged:
Jan 11 23:16:22 duo2fa-test-free sshd[9694]: Aborted Duo login for 'lookcrabs' from 172.16.128.112: User enrollment required
Jan 11 23:16:23 duo2fa-test-free sshd[9699]: Aborted Duo login for 'lookcrabs' from 172.16.128.112: User enrollment required
Jan 11 23:16:23 duo2fa-test-free sshd[9691]: Postponed keyboard-interactive for lookcrabs from 172.16.128.112 port 34466 ssh2 [preauth]
Jan 11 23:16:23 duo2fa-test-free sshd[9691]: Failed keyboard-interactive/pam for lookcrabs from 172.16.128.112 port 34466 ssh2
Jan 11 23:16:23 duo2fa-test-free sshd[9691]: Connection closed by 172.16.128.112 [preauth]


The documentation shows that after first login I should be able to enroll my mobile device but that doesn't seem to be the case. I can see that it is indeed getting out and contacting the duo endpoint via my squid logs:

    ==> /var/log/squid3/access.log <==
    1484176773.337    316 my_ip TCP_MISS/200 3627 CONNECT api-ENDPOINT.duosecurity.com:443 - HIER_DIRECT/api.endpoint.ip -
    1484176773.615    267 my_ip TCP_MISS/200 3627 CONNECT api-ENDPOINT.duosecurity.com:443 - HIER_DIRECT/api.endpoint.ip - 
    1484176773.917    292 my_ip TCP_MISS/200 3627 CONNECT api-ENDPOINT.duosecurity.com:443 - HIER_DIRECT/api.endpoint.ip -

but I am not receiving a prompt on my phone or a link to any qr to enroll a device.

I thought this may be due to the fact that I do not have any "users" set up in the duo dashboard. I have added 2 users which match the same name (ubuntu and lookcrabs). The login still fails. 

Is it possible to have ubuntu/linux users with different duo users through pam? I was under the impression that:
   1.) if the user didn't have duo set up that they would be prompted to add an authenticator/mobile device and 
  2.) that the users didn't have to be setup before hand and didn't have to match any duo user? is this not the case?

The only way I seem to be able to get the duo package working is by installing a local instance of login_duo and specifying a command in my /home/$(user)/.ssh/authorized_keys file similar to the following:

    command="/home/${user}/bin/login_duo -f ${my_duo_email} -c /home/${user}/.conf/duo_pam.conf"

**Comment by BradleyHiggins** [comment]
Hi Seapasulli,
  Please make the permissions of /etc/duo/login_duo.conf 600, owned by user 'sshd' and group 'root', for your original login_duo issue.

  For pam_duo, you should be able to enroll and 2fa as different users.  What does your ssh client report on the command line when your authentication fails?

**Comment by seapasulli** [comment]
@BradleyHiggins sorry for the late rely. We ended up using a different 2fa client due to time restrictions. My users were being reported as root but I think I must have configured something wrong. I'm closing this if that's okay.
