### ISSUE TITLE
Unsafe operation in pam_duo.c

### ISSUE THREAD

**Issue by Dr-Syn** [duosecurity/duo_unix#92]
Good afternoon;

In pam_duo.c there's several instances of "strcmp" - lines 146, 184, 191, and 193. 

You've got strncmp already in there in several places, so I assume this was an oversight and you already know why strcmp is not recommended.

That aside, though, I'm a little curious about the mechanism in the section under 177, marked 'service specific behavior' - if I'm reading that correctly, that's comparing the command string entered on the CLI against a blacklist of privesc type commands? So if I were to, for instance, 

`ln -s /usr/local/bin/sudo ~/escalate`

...that'd presumably bypass that check? Am I understanding this correctly?

If I am, then perhaps restricting privilege-escalatory command activity to, say, group 'wheel' or the like as part of the installation of the module [with the requisite chmod a-r on the directory containing such binaries, to avoid such bypasses if you're not part of the group] and avoiding checks of the command to be executed at all might be more apropos.

**Comment by robertdavidgraham** [comment]
The function `strcmp()` is not an unsafe/banned functions. Read the various standards that ban `strcpy()` and you'll see they don't ban `strcmp()`.

They use `strcnmp()` to match prefixes, and `strcmp()` to match whole strings. This is not inconsistent. You do not want to use `strncmp()` to match whole strings.

You are not reading it correctly. It's not reading the command string entered on the CLI. The "PAM service name" is set by the services themselves when they interact with PAM. You can see where it's set in the sudo source code. It's always the same regardless of what you rename `sudo` to.

**Comment by jonoberheide** [comment]
Thanks @robertdavidgraham!

@Dr-Syn: In the future, if you think you've discovered a security issue, you can report it to security@duo.com!

https://duo.com/legal/security-response
