### ISSUE TITLE
Add "failmode" to the PAM configuration

### ISSUE THREAD

**Issue by gheja** [duosecurity/duo_unix#94]
The `failmode` is set to `safe` by default (that is: allow login on configuration failure and if Duo API host is unreachable) and is not part of the configuration.

I think this can be dangerous and if the user should be aware of this.

I have [read that](https://github.com/duosecurity/duo_unix/issues/88#issuecomment-260737284)

> we choose to default to `failmode=safe` because if you mess up your config on Duo Unix you could be locked out of your system and have no way to fix it

but in some cases (for example mine, of course) the `secure` behavior is expected (from previous experiences) and there are alternative means of login (pubkey, local login, KVM over IP for example) and currently the user needs to consult the manual.

Opened a PR for this.

**Comment by xdesai** [comment]
We ended up doing this. Closing this out now. Thanks for the suggestion on how to keep our customers more aware of default behavior!
