### ISSUE TITLE
RHEL 7.3 with 1.10.0

### ISSUE THREAD

**Issue by leitu** [duosecurity/duo_unix#99]
OS: Red Hat Enterprise Linux Server release 7.3 (Maipo)
App: 1.10.0

we are upgrade duo_unix to  duo_unix.x86_64 0:1.10.0-0.el6 and in the secure log. it will show
```bash
Couldn't connect to api-xyz.duosecurity.com: Failed to connect
```

if we downgrade to  duo_unix.x86_64 0:1.9.21-0.el6, the error will gone

**Comment by mschwager** [comment]
Hey @leitu!

Thanks for notifying us about this! We'll start investigating as soon as possible :)

**Comment by bwithem** [comment]
Hey there @leitu same issue on CentOS 7.4.

**Comment by xdesai** [comment]
Are you guys using selinux?

**Comment by bwithem** [comment]
Hey @xdesai I commented here as a reminder to come back when I had a test environment to repro in. I had to deploy my production use case on Centos 6 to get unblocked.

Yes, we are using Selinux, and just confirmed that `setenforce 0` unblocks Duo. However I can't find any related AVC denial in the audit logs.

```
ausearch -ts today -m avc -m user_avc -m selinux_err
```

Selinux module is enabled
```
semodule -l | grep duo
   authlogin_duo	1.0
```

Checking `authlogin_yubikey` bool mentioned in #85, unfortunately enabling this bool does not resolve the issue.
```
getsebool authlogin_yubikey
  authlogin_yubikey --> off

setsebool -P authlogin_yubikey=1
```

**Comment by bwithem** [comment]
Realized I am on the wrong release, will need to swap to the el7 branch and do more testing.

**Comment by AaronAtDuo** [comment]
@bwithem Sorry this dropped off the radar - Did you get things working with the el7 branch?

**Comment by schafly** [comment]
@AaronAtDuo has this been resolved?  I know it has been sometime but I am also seeing the same issue on all of my Centos 7 boxes using the PAM duo installation.  If I use login_duo instead it does work.

**Comment by AaronAtDuo** [comment]
@schafly and others,

Unfortunately, Duo has not been able to reproduce this issue internally, so we are still in the dark on root cause and any possible approaches for addressing the problem.

We're definitely looking for help in this investigation, as it seems to be related to something environmental that somehow isn't affecting us.

Aaron

**Comment by vbscott** [comment]
I am going to close out this issue.  Let us know if you have this problem again.
